# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "rake"
gem "slim"
gem "sass"
gem "pry"
gem "sqlite3"
gem "data_mapper"
gem "dm-sqlite-adapter"
gem "minitest"
gem "minitest-reporters"
gem "rack-test"
